language: go
go:
- '1.6.3'
notifications:
    email:
        on_success: change
install:
- go get -v ./... github.com/ugorji/go/codec/codecgen
script:
- go generate -v -x -tags 'generate' ./...
- go build -v ./...
- go test -v ./...
